#!/usr/bin/env bash

# New exercises are released every day at midnight EST.
TODAY=$(TZ=America/New_York date +%d)
THIS_YEAR=$(TZ=America/New_York date +%Y)

# May include leading zeroes; e.g. 01, 25
PADDED_DAY=$TODAY

# Strip any leading zeroes; e.g. 00 -> 0, 0001 -> 1, 25 -> 25
[[ "$PADDED_DAY" =~ ^0*([0-9]+)$ ]] && DAY=${BASH_REMATCH[1]}

NEW_DIR="day${PADDED_DAY}"

# Create the new day's directory and copy the template files
mkdir -p "${NEW_DIR}"
touch "${NEW_DIR}/sample.txt"
touch "${NEW_DIR}/sample_output.pt1.txt"
touch "${NEW_DIR}/sample_output.pt2.txt"
touch "${NEW_DIR}/input.txt"

# Ensure we aren't going to overwrite code we've already written
if [[ ! -f "${NEW_DIR}/main.ts" ]]; then
  echo "console.log('hello, day ${DAY}!')"> "${NEW_DIR}/main.ts"
fi

# Download the AoC input file for the day using a saved session cookie
AOC_SESSION=$(cat aoc_session_cookie.txt)
curl --silent -o "${NEW_DIR}/input.txt" "https://adventofcode.com/${THIS_YEAR}/day/${DAY}/input" --cookie "session=${AOC_SESSION}"

# Temporarily download the AoC story HTML for the day using a saved session cookie
curl --silent -o "${NEW_DIR}/story.html" "https://adventofcode.com/${THIS_YEAR}/day/${DAY}" --cookie "session=${AOC_SESSION}"

# Parse the story HTML to extract the sample input and output
perl -ne '$/ = undef; print "$1" and exit 0 if /<pre><code>(.+?)<\/code><\/pre>/s' "${NEW_DIR}/story.html" > "${NEW_DIR}/sample.txt"
perl -ne '$/ = undef; print "$1" and exit 0 if /<code><em>(.+?)<\/em><\/code>/s' "${NEW_DIR}/story.html" > "${NEW_DIR}/sample_output.pt1.txt"
perl -ne '$/ = undef; print "$1" and exit 0 if /<h2 id="part2">.+?<code><em>(.+?)<\/em><\/code>/s' "${NEW_DIR}/story.html" > "${NEW_DIR}/sample_output.pt2.txt"

SAMPLE_OUTPUT_PART2_FILESIZE=$(wc -c "${NEW_DIR}/sample_output.pt2.txt" | awk '{print $1}')
if [[ "$SAMPLE_OUTPUT_PART2_FILESIZE" -eq 0 ]]; then
  echo "⛔️ WARNING: Unable to download the sample output for Part 2 until you've completed Part 1." >&2
  echo "ℹ️ You can safely run this script again after submitting your answer to Part 1!" >&2
fi

# Remove the story HTML file
rm "${NEW_DIR}/story.html"

# Finally, open the day in the browser for easier viewing as well
open "https://adventofcode.com/${THIS_YEAR}/day/${DAY}"
